# Site wide configuration

title: Avogadro
locale: en_US
description: Avogadro - the advanced molecular editor and visualizer
logo: logo.png
search: true
#url: http://avogadro.cc
url:
categories:  [Commands, Rendering, Tools, Tutorials, Teaching, Releases, Developer]
latest:
   version: "1.1.1"
   date: "11 December, 2013"

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Avogadro
  twitter: AvogadroChem
  github: avogadro
  avatar: logo.png
#  email: avogadro-devel@lists.sourceforge.net
#  google:
#    analytics:
#    verify:
#  bing-verify:
